type Arr = Array<string>;
interface Level {
    task: string;
    result: Arr;
    markup: Arr;
    classPizza: string;
    class: Array<Arr>;
}

export type LevelsSettings = Array<Level>;
export const levelsSettings: LevelsSettings = [
    {
        task: 'Select all tomatoes',
        result: ['tomato'],
        markup: [
            `&lt tomato &gt &lt/ tomato &gt`,
            `&lt tomato &gt &lt/ tomato &gt`,
            `&lt tomato &gt &lt/ tomato &gt`,
            `&lt tomato &gt &lt/ tomato &gt`,
        ],
        classPizza: 'pizza_4el',
        class: [
            ['redTomato', 'elPizza_correct'],
            ['redTomato', 'elPizza_correct'],
            ['redTomato', 'elPizza_correct'],
            ['redTomato', 'elPizza_correct'],
        ],
    },
    {
        task: 'Select red tomatoes',
        result: ['.redTomato'],
        markup: [
            `&lt tomato class="redTomato" &gt &lt/ tomato &gt`,
            `&lt tomato class="yellowTomato" &gt &lt/ tomato &gt`,
            `&lt tomato class="redTomato" &gt &lt/ tomato &gt`,
            `&lt tomato class="yellowTomato" &gt &lt/ tomato &gt`,
        ],
        classPizza: 'pizza_4el',
        class: [
            ['redTomato', 'elPizza_correct'],
            ['yellowTomato', 'elPizza'],
            ['redTomato', 'elPizza_correct'],
            ['yellowTomato', 'elPizza'],
        ],
    },
    {
        task: 'Select a rotten tomato',
        result: ['#rottenRedTomato', 'tomato:nth-child(2)', 'tomato:nth-of-type(2)'],
        markup: [
            `&lt tomato &gt &lt/ tomato &gt`,
            `&lt tomato id="rottenRedTomato" &gt &lt/ tomato &gt`,
            `&lt tomato &gt &lt/ tomato &gt`,
            `&lt tomato &gt &lt/ tomato &gt`,
        ],
        classPizza: 'pizza_4el',
        class: [
            ['redTomato', 'elPizza'],
            ['rottenRedTomato', 'elPizza_correct'],
            ['redTomato', 'elPizza'],
            ['redTomato', 'elPizza'],
        ],
    },
    {
        task: 'Select sausages and  red tomatoes',
        result: ['.redTomato, sausage', 'sausage, .redTomato'],
        markup: [
            `&lt tomato class="redTomato" &gt &lt/ tomato &gt`,
            `&lt sausage  &gt &lt/ sausage &gt`,
            `&lt tomato class="yellowTomato" &gt &lt/ tomato &gt`,
            `&lt sausage &gt &lt/ sausage &gt`,
            `&lt sausage &gt &lt/ sausage &gt`,
            `&lt tomato class="redTomato" &gt &lt/ tomato &gt`,
        ],
        classPizza: 'pizza_6el',
        class: [
            ['redTomato', 'elPizza_correct'],
            ['sausage', 'elPizza_correct'],
            ['yellowTomato', 'elPizza'],
            ['sausage', 'elPizza_correct'],
            ['sausage', 'elPizza_correct'],
            ['redTomato', 'elPizza_correct'],
        ],
    },
    {
        task: 'Select small tomatoes',
        result: ['[size="small"]', '[size = "small"]', 'tomato[size="small"]'],
        markup: [
            `&lt tomato class="redTomato" &gt &lt/ tomato &gt`,
            `&lt sausage  &gt &lt/ sausage &gt`,
            `&lt tomato class="yellowTomato" &gt &lt/ tomato &gt`,
            `&lt tomato size="small" &gt &lt/ tomato &gt`,
            `&lt sausage &gt &lt/ sausage &gt`,
            `&lt tomato size="small" &gt &lt/ tomato &gt`,
        ],
        classPizza: 'pizza_6el',
        class: [
            ['redTomato', 'elPizza'],
            ['sausage', 'elPizza'],
            ['yellowTomato', 'elPizza'],
            ['redTomato-small', 'elPizza_correct'],
            ['sausage', 'elPizza'],
            ['redTomato-small', 'elPizza_correct'],
        ],
    },
    {
        task: 'Select a small red tomato',
        result: ['.redTomato[size="small"]', '.red[size = "small"]', 'tomato:nth-child(4)', 'tomato:nth-of-type(3)'],
        markup: [
            `&lt tomato class="yellowTomato" size="small" &gt &lt/tomato &gt`,
            `&lt sausage  &gt &lt/ sausage &gt`,
            `&lt tomato class="yellowTomato" &gt &lt/ tomato &gt`,
            `&lt tomato class="redTomato" size="small" &gt &lt/tomato &gt`,
            `&lt sausage &gt &lt/ sausage &gt`,
            `&lt tomato class="redTomato" &gt &lt/tomato &gt`,
        ],
        classPizza: 'pizza_6el',
        class: [
            ['yellowTomato-small', 'elPizza'],
            ['sausage', 'elPizza'],
            ['yellowTomato', 'elPizza'],
            ['redTomato-small', 'elPizza_correct'],
            ['sausage', 'elPizza'],
            ['redTomato', 'elPizza'],
        ],
    },
    {
        task: 'Select a rotten red tomato',
        result: [
            '.redTomato.rotten',
            '.rotten.redTomato',
            'tomato:last-child',
            'tomato:last-of-type',
            '.redTomato:last-child',
            '.redTomato:last-of-type',
            '.rotten:last-child',
            '.rotten:last-of-type',
        ],
        markup: [
            `&lt tomato class="yellowTomato" &gt &lt/ tomato &gt`,
            `&lt tomato  class="yellowTomato rotten" &gt &lt/ tomato &gt`,
            `&lt tomato class="redTomato" &gt &lt/ tomato &gt`,
            `&lt tomato class="redTomato rotten" &gt &lt/ tomato &gt`,
        ],
        classPizza: 'pizza_4el',
        class: [
            ['yellowTomato', 'elPizza'],
            ['rottenYellowTomato', 'elPizza'],
            ['redTomato', 'elPizza'],
            ['rottenRedTomato', 'elPizza_correct'],
        ],
    },
    {
        task: 'Choose pizza, tomatoes and sausages with one selector',
        result: ['*'],
        markup: [
            `&lt tomato class="redTomato" &gt &lt/ tomato &gt`,
            `&lt sausage  &gt &lt/ sausage &gt`,
            `&lt tomato class="yellowTomato" &gt &lt/ tomato &gt`,
            `&lt sausage &gt &lt/ sausage &gt`,
            `&lt tomato class="yellowTomato" &gt &lt/ tomato &gt`,
            `&lt sausage &gt &lt/ sausage &gt`,
        ],
        classPizza: 'pizza_6el',
        class: [
            ['redTomato', 'elPizza_correct'],
            ['sausage', 'elPizza_correct'],
            ['yellowTomato', 'elPizza_correct'],
            ['sausage', 'elPizza_correct'],
            ['yellowTomato', 'elPizza_correct'],
            ['redTomato', 'elPizza_correct'],
        ],
    },
    {
        task: 'Сhoose the red tomatoes that are located after the sausage',
        result: ['sausage + .redTomato', 'sausage ~ .redTomato'],
        markup: [
            `&lt tomato class="redTomato" &gt &lt/ tomato &gt`,
            `&lt sausage  &gt &lt/ sausage &gt`,
            `&lt tomato class="redTomato" &gt &lt/ tomato &gt`,
            `&lt sausage &gt &lt/ sausage &gt`,
            `&lt sausage &gt &lt/ sausage &gt`,
            `&lt tomato class="redTomato" &gt &lt/ tomato &gt`,
        ],
        classPizza: 'pizza_6el',
        class: [
            ['redTomato', 'elPizza'],
            ['sausage', 'elPizza'],
            ['redTomato', 'elPizza_correct'],
            ['sausage', 'elPizza'],
            ['sausage', 'elPizza'],
            ['redTomato', 'elPizza_correct'],
        ],
    },
    {
        task: 'Choose a small red tomato that is right after the sausage',
        result: [
            'sausage + .redTomato[size="small"]',
            'sausage + .redTomato[size = "small"]',
            'tomato:nth-child(5)',
            'tomato:nth-of-type(3)',
            '.redTomato:nth-child(5)',
            '.redTomato:nth-of-type(3)',
            '[size="small"]:nth-child(5)',
            '[size="small"]:nth-of-type(2)',
        ],
        markup: [
            `&lt tomato class="redTomato"  size="small" &gt &lt/tomato &gt`,
            `&lt sausage  &gt &lt/ sausage &gt`,
            `&lt tomato class="redTomato" &gt &lt/ tomato &gt`,
            `&lt sausage &gt &lt/ sausage &gt`,
            `&lt tomato class="redTomato"  size="small" &gt &lt/tomato &gt`,
            `&lt tomato class="redTomato"  size="small" &gt &lt/tomato &gt`,
        ],
        classPizza: 'pizza_6el',
        class: [
            ['redTomato-small', 'elPizza'],
            ['sausage', 'elPizza'],
            ['redTomato', 'elPizza'],
            ['sausage', 'elPizza'],
            ['redTomato-small', 'elPizza_correct'],
            ['redTomato-small', 'elPizza'],
        ],
    },
    {
        task: 'Choose the red small tomatoes that are located after the sausage using the selector "~"',
        result: [
            'sausage ~ .redTomato[size="small"]',
            'sausage ~ .redTomato[size = "small"]',
            'sausage ~ tomato[size="small"]',
            'sausage ~ .tomato[size = "small"]',
        ],
        markup: [
            `&lt tomato class="redTomato"  size="small" &gt &lt/tomato &gt`,
            `&lt sausage  &gt &lt/ sausage &gt`,
            `&lt tomato class="redTomato" &gt &lt/ tomato &gt`,
            `&lt sausage &gt &lt/ sausage &gt`,
            `&lt tomato class="redTomato"  size="small" &gt &lt/tomato &gt`,
            `&lt tomato class="redTomato"  size="small" &gt &lt/tomato &gt`,
        ],
        classPizza: 'pizza_6el',
        class: [
            ['redTomato-small', 'elPizza'],
            ['sausage', 'elPizza'],
            ['redTomato', 'elPizza'],
            ['sausage', 'elPizza'],
            ['redTomato-small', 'elPizza_correct'],
            ['redTomato-small', 'elPizza_correct'],
        ],
    },
];
